name: JSON Syntax Check

on:
  push:
    paths:
      - 'translations/**.json'
  pull_request:

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
